bcgov/cas-airflow

- dags/stream_minio_kubernetes_pod.py
- docker/stream-minio/bin/wget-spider.sh
- docker/stream-minio/init.sh
- update dags to point to the correct namespace
- add logs in scripts inside dag image
> update dag and logs inside image

- dags/remove-child-process-logs.py
> fix: fix typo in dag task

- .gitignore
- Readme.md
- requirements.txt
> fix(readme): local development instructions reflect repo structure

- .gitignore
- dags/ggircs_deploy_db.py
- dags/trigger_k8s_cronjob.py
- Adds a function that retrieves a cronjob and creates a job pod from it
> feat: trigger_k8s_cronjob

- dags/trigger_k8s_cronjob.py
- helm/airflow/templates/role.yaml
> fix: allow airflow to list cronjobs, and raise an exception if it can't

- dags/ciip_deploy_db.py
adds the dag for deploying the ciip portal by cronjob names
> feat: ciip-portal deploy db dag

- dags/swrs_eccc_import.py
- uses cronjobs for the load functions
> swrs_eccc_import by cronjob

- helm/cas-airflow/Chart.yaml
- helm/cas-airflow/values.yaml
was set to default (16), we wanted it set to 1 as per https://youtrack.button.is/issue/GGIRCS-1832
> feat: update dag_concurrency to be 1

- dags/remove_old_processor_logs.py
DAG removes old processor log files on a schedule
> fix: remove old processor log files

- dags/exec_in_pod.py
- dags/remove_old_processor_logs.py
- dags/walg_backup.py
make exec_in_pod function generic, make dags specify a selector
> feat: generic exec_in_pod

- .circleci/config.yml
Updates this repository to use our GCP registry
> feat: creating new ci job that deploys to gcp/gcr

- dags/ggircs_ciip_load_testing_data.py
pretty much the same as ciip-deploy-db but with a cas-ggircs cronjob & some different flags in the ciip-deploy script
> chore: load-testing dag

- helm/cas-airflow/Chart.lock
- helm/cas-airflow/Chart.yaml
This reverts commit 56a6a09348902bdad2747d3a2dc382a8c4c373ef.
> Revert "chore: update cas-postgres chart to 0.8.1"

- helm/cas-airflow-dag-trigger/Chart.yaml
Bump version to get new defaults
> chore: update chart version

- helm/cas-airflow/Chart.yaml
> chore: bump chart version

- helm/cas-airflow/Chart.lock
- helm/cas-airflow/Chart.yaml
- helm/cas-airflow/values.yaml
- update Airflow, 1.0.0 chart is deleted atm.
> chore: update airflow to 2.1.2

- dags/walg_backup.py
- dags/walg_backup_dags.py
- dags/walg_backups.py
Implementation for https://github.com/bcgov/cas-airflow/issues/104
> Feat: backup library to create tasks

- helm/cas-airflow/values.yaml
https://github.com/apache/airflow/blob/0e0e88792b04c78c2b0d5114e0078be847270da9/airflow/models/dag.py#L2338
Try setting some global conf for dag pausing.
> fix: dags paused at creation

- dags/fetch_and_save_dag_from_github.py
- use python `time.sleep` instead of an airflow time sensor.
> refactor: use python time.sleep

- dags/dag_configuration.py
update the email array to notify Matthieu, Dylan & Pierre on failure
> chore: update default email on failure notification

- .tool-versions
- Readme.md
Update readme instructions and tools to current versions
No card
> chore: update dependencies

- helm/cas-airflow/values.yaml
> chore: fix yaml

- helm/cas-airflow/values.yaml
Increases the timeoutSeconds & periodSeconds of startupProbe
> chore: startupProbe timeout

- Dockerfile
- helm/cas-airflow/Chart.lock
- helm/cas-airflow/Chart.yaml
- helm/cas-airflow/values.yaml
Update to 2.10.1 as recommended by airflow team
> chore: release v2.10.1

- .github/workflows/release.yaml
- helm/cas-airflow/Chart.yaml
Pining a release prior to all Airflow 3 upgrades.
> chore: release v2.2.0
